// {
//     "alias": "molinari-delicatessen-san-francisco",
//     "name": "Molinari Delicatessen",
//     "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/B5vUs6hU1W6UcBQL52v2GQ/o.jpg",
//     "is_closed": false,
//     "url": "https://www.yelp.com/biz/molinari-delicatessen-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw",
//     "review_count": 1154,
//     "categories": "Delis",
//     "rating": 4.5,
//     "transactions": "pickup,delivery",
//     "price": "$$",
//     "location": "373 Columbus Ave, San Francisco, CA 94133",
//     "display_phone": "(415) 421-2337",
//     "distance": 1453.998141679007
// },
// {

//     "alias": "deli-board-san-francisco",
//     "name": "Deli Board",
//     "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/m5dL_mNk9rjSJ5jQu17hVw/o.jpg",
//     "is_closed": false,
//     "url": "https://www.yelp.com/biz/deli-board-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw",
//     "review_count": 1413,
//     "categories": "Delis",
//     "rating": 4.5,
//     "transactions": "delivery",
//     "price": "$$",
//     "location": "1058 Folsom St, San Francisco, CA 94103",
//     "display_phone": "(415) 552-7687",
//     "distance": 1201.0092939107112
// },
// {
//     "alias": "wise-sons-san-francisco-6",
//     "name": "Wise Sons",
//     "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/O6Apf39llWL3sfye-PseNQ/o.jpg",
//     "is_closed": false,
//     "url": "https://www.yelp.com/biz/wise-sons-san-francisco-6?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw",
//     "review_count": 302,
//     "categories": "Sandwiches",
//     "rating": 3.5,
//     "transactions": "",
//     "price": "$$",
//     "location":  "736 Mission St, San Francisco, CA 94103",
//     "display_phone": "(415) 655-7887",
//     "distance": 314.79308965734816
// },
// {
//     "alias": "sammys-on-2nd-san-francisco",
//     "name": "Sammy's on 2nd",
//     "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/vi6h1mfMkRwIkyj5VE66FQ/o.jpg",
//     "is_closed": false,
//     "url": "https://www.yelp.com/biz/sammys-on-2nd-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw",
//     "review_count": 207,
//     "categories": "sandwiches",
//     "rating": 4.0,
//     "transactions": "delivery",
//     "price": "$",
//     "location": "84 2nd St, San Francisco, CA 94105",
//     "display_phone": "(415) 243-0311",
//     "distance": 146.3807329561209
// },
// {

//     "alias": "limoncello-san-francisco",
//     "name": "Limoncello",
//     "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/GNMz7gMIMgmBZr4WAYUQsw/o.jpg",
//     "is_closed": false,
//     "url": "https://www.yelp.com/biz/limoncello-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw",
//     "review_count": 1124,
//     "categories": "Beer, Wine & Spirits",
//     "rating": 5.0,
//     "transactions": "pickup, delivery",
//     "price": "$$",
//     "location": "1400 Sutter St, San Francisco, CA 94109",
//     "display_phone": "(415) 638-6361",
//     "distance": 2076.1540447650927
// },
// {

//     "alias": "sutter-st-cafe-san-francisco",
//     "name": "Sutter St. Cafe",
//     "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/4ANprW476nocK3E8UT9N1g/o.jpg",
//     "is_closed": false,
//     "url": "https://www.yelp.com/biz/sutter-st-cafe-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw",
//     "review_count": 208,
//     "categories": "cafes",
//     "rating": 4.5,
//     "transactions": "pickup, delivery",
//     "price": "$",
//     "location": "450 Sutter St, San Francisco, CA 94108",
//     "display_phone": "(415) 362-8342",
//     "distance": 737.7876443304846
// },
// {

//     "alias": "5th-avenue-deli-and-market-san-francisco",
//     "name": "5th Avenue Deli & Market",
//     "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/dD3LeuzL_TQSUdcHKIBPHw/o.jpg",
//     "is_closed": false,
//     "url": "https://www.yelp.com/biz/5th-avenue-deli-and-market-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw",
//     "review_count": 57,
//     "categories": "Sandwiches",
//     "rating": 4.5,
//     "transactions": "pickup, delivery",
//     "price": "$",
//     "location": "4 Embarcadero Ctr, San Francisco, CA 94111",
//     "display_phone": "(415) 757-0950",
//     "distance": 1005.1478381004005
// },
// {

//     "alias": "sf-deli-and-wine-san-francisco-3",
//     "name": "SF Deli & Wine",
//     "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/JZyTwN-b1HEGQsJmnqjybQ/o.jpg",
//     "is_closed": false,
//     "url": "https://www.yelp.com/biz/sf-deli-and-wine-san-francisco-3?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw",
//     "review_count": 29,
//     "categories": "Beer, Wine & Spirits",
//     "rating": 4.0,
//     "transactions": "pickup, delivery",
//     "price": "$",
//     "location": "810 Mission St, San Francisco, CA 94103",
//     "display_phone": "(415) 512-7847",
//     "distance": 556.544681533414
// },

// {

//     "alias": "liquor-and-deli-on-union-square-san-francisco",
//     "name": "Liquor & Deli On Union Square",
//     "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/tro4pbb5r_aMt7dmmti_4g/o.jpg",
//     "is_closed": false,
//     "url": "https://www.yelp.com/biz/liquor-and-deli-on-union-square-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw",
//     "review_count": 37,
//     "categories": "Beer, Wine & Spirits",
//     "rating": 4.0,
//     "transactions": "pickup, delivery",
//     "price": "$",
//     "location": "423 Stockton St, San Francisco, CA 94108",
//     "display_phone": "(415) 434-8210",
//     "distance": 729.9634773299399
// },
// {

//     "alias": "the-boys-deli-san-francisco",
//     "name": "The Boys’ Deli",
//     "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/qXbjX3opOgmgN_5NsCb9Cw/o.jpg",
//     "is_closed": false,
//     "url": "https://www.yelp.com/biz/the-boys-deli-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw",
//     "review_count": 336,
//     "categories": "Breakfast & Brunch",
//     "rating": 4.5,
//    "transactions": "pickup, delivery",
//     "price": "$$",
//     "location": "2222 Polk St,San Francisco, CA 94109",
//     "display_phone": "(415) 776-3099",
//     "distance": 2235.2674125931903
// },
// {

//     "alias": "palermo-ii-delicatessen-san-francisco",
//     "name": "Palermo II Delicatessen",
//     "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/47DciaUfzII175Wj4Stm_w/o.jpg",
//     "is_closed": false,
//     "url": "https://www.yelp.com/biz/palermo-ii-delicatessen-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw",
//     "review_count": 78,
//     "categories": "Delis",
//     "rating": 5.0,
//     "transactions": "pickup, delivery",
//     "price": "$$",
//     "location": "658 Vallejo St, San Francisco, CA 94133",
//     "display_phone": "(415) 937-0161",
//     "distance": 1517.0065811617371
// },
// {

//     "alias": "working-girls-cafe-san-francisco-3",
//     "name": "Working Girls' Cafe",
//     "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/LLI6Afy68RS_uqezhBNdBQ/o.jpg",
//     "is_closed": false,
//     "url": "https://www.yelp.com/biz/working-girls-cafe-san-francisco-3?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw",
//     "review_count": 418,
//     "categories": "Sandwiches",
//     "rating": 4.0,
//     "transactions": "pickup, delivery",
//     "price": "$$",
//     "location": "122 New Montgomery St, San Francisco, CA 94105",
//     "display_phone": "(415) 537-1170",
//     "distance": 28.22725630514869
// },
