CREATE TABLE whattoeat_restaurants (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    alias TEXT,
    name TEXT NOT NULL,
    rating FLOAT CONSTRAINT chk_rating CHECK (rating >= 0 AND rating <= 5),
    image_url TEXT,
    url TEXT,
    review_count INTEGER,
    is_closed BOOLEAN,
    price TEXT,
    location TEXT,
    display_phone TEXT,
    distance TEXT,
    categories TEXT,
    transactions TEXT
);



