CREATE TABLE restaurant_detail (
    restaurant_id INTEGER REFERENCES whattoeat_restaurants(id) ON DELETE CASCADE NOT NULL,
    dish_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dish_name TEXT,
    dish_description TEXT,
    dish_price TEXT
);