CREATE TABLE dishes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    restaurant_id INTEGER REFERENCES whattoeat_restaurants(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    dish_price TEXT,
    dish_img TEXT,
    dish_desc TEXT
);