BEGIN;

TRUNCATE
  whattoeat_restaurants,
  restaurant_detail
  RESTART IDENTITY CASCADE;

INSERT INTO whattoeat_restaurants (alias, name, image_url, is_closed, url, review_count, categories, rating, transactions, price, location, display_phone, distance)
VALUES
('molinari-delicatessen-san-francisco',
            'Molinari Delicatessen',
            'https://s3-media3.fl.yelpcdn.com/bphoto/B5vUs6hU1W6UcBQL52v2GQ/o.jpg',
             false,
            'https://www.yelp.com/biz/molinari-delicatessen-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw',
            1154,
            'Delis',
            4.5,
            'pickup,delivery',
            '$$',
            '373 Columbus Ave, San Francisco, CA 94133',
            '(415) 421-2337',
            1453.998141679007),

('deli-board-san-francisco',
            'Deli Board',
            'https://s3-media3.fl.yelpcdn.com/bphoto/m5dL_mNk9rjSJ5jQu17hVw/o.jpg',
            false,
           'https://www.yelp.com/biz/deli-board-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw',
            1413,
            'Delis',
            4.5,
            'delivery',
            '$$',
            '1058 Folsom St, San Francisco, CA 94103',
            '(415) 552-7687',
            1201.0092939107112),
            (
'wise-sons-san-francisco-6',
            'Wise Sons',
            'https://s3-media2.fl.yelpcdn.com/bphoto/O6Apf39llWL3sfye-PseNQ/o.jpg',
            false,
            'https://www.yelp.com/biz/wise-sons-san-francisco-6?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw',
            302,
            'Sandwiches',
            3.5,
            'delivery',
            '$$',
            '736 Mission St, San Francisco, CA 94103',
            '(415) 655-7887',
            314.79308965734816
            ),
            (
'sammys-on-2nd-san-francisco',
            'Sammy’s on 2nd',
            'https://s3-media2.fl.yelpcdn.com/bphoto/vi6h1mfMkRwIkyj5VE66FQ/o.jpg',
            false,
            'https://www.yelp.com/biz/sammys-on-2nd-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw',
            207,
            'Sandwiches',
            4.0,
            'delivery',
            '$',
            '84 2nd St, San Francisco, CA 94105',
            '(415) 243-0311',
            146.3807329561209
            ),
            (
'limoncello-san-francisco',
            'Limoncello',
            'https://s3-media2.fl.yelpcdn.com/bphoto/GNMz7gMIMgmBZr4WAYUQsw/o.jpg',
            false,
            'https://www.yelp.com/biz/limoncello-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw',
            1124,
            'Beer, Wine & Spirits',
            5.0, 
            'pickup, delivery',
            '$$',
            '1400 Sutter St, San Francisco, CA 94109',
            '(415) 638-6361',
            2076.1540447650927
            ),
            (
 'sutter-st-cafe-san-francisco',
            'Sutter St. Cafe',
            'https://s3-media1.fl.yelpcdn.com/bphoto/4ANprW476nocK3E8UT9N1g/o.jpg',
            false,
            'https://www.yelp.com/biz/sutter-st-cafe-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw',
            208,
            'cafes',
            4.5,
            'pickup, delivery',
            '$',
            '450 Sutter St, San Francisco, CA 94108',
            '(415) 362-8342',
            737.7876443304846
            ),
            (
'5th-avenue-deli-and-market-san-francisco',
            '5th Avenue Deli & Market',
            'https://s3-media4.fl.yelpcdn.com/bphoto/dD3LeuzL_TQSUdcHKIBPHw/o.jpg',
            false,
            'https://www.yelp.com/biz/5th-avenue-deli-and-market-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw',
            57,
            'Sandwiches',
            4.5,
            'pickup, delivery',
            '$',
            '4 Embarcadero Ctr, San Francisco, CA 94111',
            '(415) 757-0950',
            1005.1478381004005
            ),
            (
'sf-deli-and-wine-san-francisco-3',
            'SF Deli & Wine',
            'https://s3-media4.fl.yelpcdn.com/bphoto/JZyTwN-b1HEGQsJmnqjybQ/o.jpg',
            false,
            'https://www.yelp.com/biz/sf-deli-and-wine-san-francisco-3?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw',
            29,
            'Beer, Wine & Spirits',
            4.0,
            'pickup, delivery',
            '$',
            '810 Mission St, San Francisco, CA 94103',
            '(415) 512-7847',
            556.544681533414
            ),
            (
'liquor-and-deli-on-union-square-san-francisco',
            'Liquor & Deli On Union Square',
            'https://s3-media4.fl.yelpcdn.com/bphoto/tro4pbb5r_aMt7dmmti_4g/o.jpg',
            false,
            'https://www.yelp.com/biz/liquor-and-deli-on-union-square-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw',
            37,
            'Beer, Wine & Spirits',
            4.0,
            'pickup, delivery',
            '$',
            '423 Stockton St, San Francisco, CA 94108',
            '(415) 434-8210',
            729.9634773299399
            ),
            (
'the-boys-deli-san-francisco',
            'The Boys’ Deli',
            'https://s3-media3.fl.yelpcdn.com/bphoto/qXbjX3opOgmgN_5NsCb9Cw/o.jpg',
            false,
            'https://www.yelp.com/biz/the-boys-deli-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw',
            336,
            'Breakfast & Brunch',
            4.5,
           'pickup, delivery',
            '$$',
            '2222 Polk St,San Francisco, CA 94109',
            '(415) 776-3099',
            2235.2674125931903
            ),
            (
'palermo-ii-delicatessen-san-francisco',
            'Palermo II Delicatessen',
            'https://s3-media4.fl.yelpcdn.com/bphoto/47DciaUfzII175Wj4Stm_w/o.jpg',
            false,
            'https://www.yelp.com/biz/palermo-ii-delicatessen-san-francisco?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw',
            78,
            'Delis',
            5.0,
            'pickup, delivery',
            '$$',
            '658 Vallejo St, San Francisco, CA 94133',
            '(415) 937-0161',
            1517.0065811617371
            ),
            (
'working-girls-cafe-san-francisco-3',
            'Working Girls’ Cafe',
            'https://s3-media3.fl.yelpcdn.com/bphoto/LLI6Afy68RS_uqezhBNdBQ/o.jpg',
            false,
            'https://www.yelp.com/biz/working-girls-cafe-san-francisco-3?adjust_creative=5Brfn2GCNjfiuMqdnkxwXw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=5Brfn2GCNjfiuMqdnkxwXw',
            418,
            'Sandwiches',
            4.0,
            'pickup, delivery',
            '$$',
            '122 New Montgomery St, San Francisco, CA 94105',
            '(415) 537-1170',
            28.22725630514869
            );

COMMIT;
